apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "syfosmrestmock"
  namespace: "default"
  labels:
    team: "teamsykefravr"
spec:
  image: "repo.adeo.no:5443/syfo/syfosmrestmock:@@VERSION@@"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
